language: node_js
node_js:
  - '4.1'
after_success:
  - npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: 6269......8f8a
    secure: r3Wa/DO6Xfv38aXPF+YeK/iqE9EJYdRqBNnYN/XKvtLYe5eMmcUNpHKiwrcjL1f60Qzpe5MMi3Mqi2F6D3c78CCH34PaKcjHpONzKMq9eWfWkVe2dgPYdPrE3OyACxGKsd7xs2p0XoojzUL1QV+zonl2+6/udCVnsa1xGrla5VivRxE2DbqMPX1GJq++GfPGfIHVICu2jpPcFLFrQuiKGFcKLM3MCI7ylDCWqHzV0Q9Jij1MuvaVe2QDYZGQrkQaRk8Hr+5u1wXYrNK9udASLpAy6xBAkyC/vSQqFBDHuC98+8u16Jw7lCyp97hgkev2ZycP+XKkq5MkwQuI6dJ3Ir8F4YXVD4N1qjZuwkMnYz4UxWhU3fEdOy6dX/QpZ0APLoA90ilj3DZaurzqqpSOt38DskUgfaXXw1X6rC9sXGU1foDjVTuzow2sNPTDobi8ob0YMDk4bywH+p9quCX95uc3NpNw8g0uxcGPafIZTBh5Lri8TdJ+GU/tt8nFSbgdmzvC+2Bz4fAnLmlEAeUOI902SNVj4tCnnBmnkTEddZL7ugQ2RrRCd5P22Z7/p9RfhgebMIwcEOgkKx49yd4COABzhNyiSWUWHS8aAHFMzLT/H2yNjt4hP4VRRLSJkcuikVSZoMBeTuuhBwQoB9bgyqP3j2/3A10SbZvMhKyVujE=
  on:
    tags: true
    all_branches: true
