language: node_js
node_js:
- '4.1'
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: jVXxWnz33GR6sAZmUNZTJwhI5xEsSHojT9BpN+FbtTlv7VCOdtmxaNPbOEvDW4dnVNRaxQB8CQQgGu/xn//UE63H7Zehq2l4vmcQZF4CvMcsZc7V5nm/66XJXLJQgVIuM3WGmOw8NtK1i0xBVtCGSN51kMqq7yLVCYcExt5Owh84k2/yTu2kOZ/pYq5cqEIJrNGAy8VpBeDTDwMrw9BbJnYEXSvf1GvSktFXeXPsLOwf4ihJf7hZt0i3SnU7+KXCzLlrjSouhJKY9Zh+/jME3cBT7ssm1AXzNmsTe6uUr7HxTO37ORvYT5qnIztJFriiFqsfeoNE+mgNEEC2J9Faoo8oSMVsbEyHfJbqKhpfFbdiXjfqM6tRoj7IBgrajIsSDVeA2zwDFzhDDWJmNfqzgkemjMuDTYx5rZTX6kBGhq3DygVqX7AqTxMp/xWxtNy1Hqx2yQOooQvUYi0G7GdEkwqlwpk5ZhyhTStEy9TlH1+d/E8dc7IeqigFZO59bCCFVQScI5iyOwub4C16x+2EbHxWTki+tZ3B/psL009nN+dI5IKouYaNuK5U7xG0h7viA1CaL9HGtdJi5wth2fRiTJXFejgd5q4SMJI4mCi+glfGvUPVqmBPQLAxdkYRDq9C3DZSI0u00Gel2Wrm/VELgtm0I7yUPRr1Y83oxKUMm44=
  on:
    tags: true
    all_branches: true

